# 準備

## Googleドライブのマウント

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [2]:
import sys
sys.path.append('/content/drive/My Drive/DNN_code_colab_lesson_1_2')

# importと関数定義

In [3]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [11]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = 0.5
b = np.array([0.5])

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
b = np.random.rand(1) * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[4 0]
shape: (2,)

*** バイアス ***
[1.03273321]
shape: (1,)

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[9.03273321]
shape: (1,)

*** 中間層出力 ***
[9.03273321]
shape: (1,)



# 順伝播（単層・複数ユニット）


In [5]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.53480533 0.53346551 0.42603807]
 [0.03722394 0.91755407 0.11927317]
 [0.94070613 0.18191074 0.07671629]
 [0.26336534 0.16195663 0.63707332]]
shape: (4, 3)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[2.43897194 5.52310073 0.8387632 ]
shape: (3,)

*** 中間層出力 ***
[0.91975124 0.99602244 0.69820467]
shape: (3,)



# 順伝播（3層・複数ユニット）

In [12]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W1'] = np.random.rand(2,3)
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W2'] = np.random.rand(3,2)
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['W3'] = np.random.rand(2,2)
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.random.rand(3)
    network['b2'] = np.array([0.1, 0.2])
    network['b2'] = np.random.rand(2)
    network['b3'] = np.array([1, 2])
    network['b3'] = np.random.rand(2)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]
shape: (2,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.10617664 0.42064717 0.8733328 ]
 [0.03364186 0.78532061 0.615109  ]]
shape: (2, 3)

*** 重み2 ***
[[0.93114547 0.45586784]
 [0.96170848 0.3808952 ]
 [0.38721086 0.70642264]]
shape: (3, 2)

*** 重み3 ***
[[0.06869698 0.49794525]
 [0.43629827 0.80751985]]
shape: (2, 2)

*** バイアス1 ***
[0.19331584 0.50786667 0.06949044]
shape: (3,)

*** バイアス2 ***
[0.1515491  0.31462296]
shape: (2,)

*** バイアス3 ***
[0.7615572  0.83679979]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[0.36677621 2.49915506 2.17304125]
shape: (3,)

*** 中間層出力1 ***
[0.36677621 2.49915506 2.17304125]
shape: (3,)

*** 総入力2 ***
[3.73795489 2.96882615]
shape: (2,)

*** 出力1 ***
[0.36677621 2.49915506 2.17304125]
shape: (3,)

出力合計: 5.038972518663849


# 多クラス分類（2-3-4ネットワーク）

In [13]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    # network['W1'] = np.array([
    #     [0.1, 0.3, 0.5],
    #     [0.2, 0.4, 0.6]
    # ])
    network['W1'] = np.random.rand(3,5)
    # network['W2'] = np.array([
    #     [0.1, 0.4, 0.7, 1.0],
    #     [0.2, 0.5, 0.8, 1.1],
    #     [0.3, 0.6, 0.9, 1.2]
    # ])
    network['W2'] = np.random.rand(5,4)
    # network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.random.rand(5)
    # network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    network['b2'] = np.random.rand(4)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.93016403 0.39578019 0.86323594 0.64389467 0.39203273]
 [0.33175114 0.27961138 0.1611105  0.31983037 0.98478388]
 [0.52023861 0.47771643 0.85420109 0.09765756 0.07131366]]
shape: (3, 5)

*** 重み2 ***
[[0.13361392 0.71637494 0.11795237 0.29524945]
 [0.12766204 0.55944784 0.65183178 0.6061149 ]
 [0.21893375 0.13445611 0.5571538  0.19813706]
 [0.18762512 0.81747764 0.64960216 0.05167609]
 [0.0292715  0.02363686 0.95127432 0.20828081]]
shape: (5, 4)

*** バイアス1 ***
[0.66511281 0.09099187 0.4060593  0.90934701 0.2692253 ]
shape: (5,)

*** バイアス2 ***
[0.8643586  0.3342321  0.31516167 0.69647228]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[3.81949495 2.4791441  4.1541195  2.48587511 2.84476676]
shape: (5,)

*** 中間層出力1 ***
[3.81949495 2.4791441  4.1541195  2.48587511 2.84476676]
shape: (5,)

*** 総入力2 ***
[3.15034901 7.11530978 9.01713192 4.87087792]
shape: (4,)

*** 出力1 ***
[0.00242473 0.12782747 0.85619966 0.01354814]
shape: (4,)

出力合計: 1.0000000000000002



# 回帰（2-3-2ネットワーク）

In [14]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    # network['W1'] = np.array([
    #     [0.1, 0.3, 0.5],
    #     [0.2, 0.4, 0.6]
    # ])
    network['W1'] = np.random.rand(3,5)
    # network['W2'] = np.array([
    #     [0.1, 0.4],
    #     [0.2, 0.5],
    #     [0.3, 0.6]
    # ])
    network['W2'] = np.random.rand(5,4)
    # network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.random.rand(5)
    # network['b2'] = np.array([0.1, 0.2])
    network['b2'] = np.random.rand(4)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 8., 16.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.60466381 0.80548001 0.15333091 0.93958995 0.23839108]
 [0.66001988 0.383976   0.6055149  0.9773219  0.36122121]
 [0.87670123 0.12560542 0.54945345 0.07919138 0.36122962]]
shape: (3, 5)

*** 重み2 ***
[[0.51143901 0.15568646 0.3011049  0.34490875]
 [0.57190602 0.20524705 0.73027722 0.89325012]
 [0.89451571 0.78604548 0.97297035 0.70129293]
 [0.05436464 0.59339508 0.13681941 0.30160526]
 [0.47311561 0.26581602 0.83800512 0.88151855]]
shape: (5, 4)

*** バイアス1 ***
[0.69324927 0.49753416 0.25168912 0.15988095 0.60551248]
shape: (5,)

*** バイアス2 ***
[0.44703404 0.10852042 0.5915207  0.24360741]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[5.24805652 2.44778242 3.26441018 3.29168884 2.65003483]
shape: (5,)

*** 中間層出力1 ***
[5.24805652 2.44778242 3.26441018 3.29168884 2.65003483]
shape: (5,)

*** 総入力2 ***
[8.88378689 6.65164039 9.80657996 9.85834325]
shape: (4,)

*** 出力1 ***
[8.88378689 6.65164039 9.80657996 9.85834325]
shape: (4,)

出力合計: 16.901972794625443



# 2値分類（2-3-1ネットワーク）

In [16]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    # network['W1'] = np.array([
    #     [0.1, 0.3, 0.5],
    #     [0.2, 0.4, 0.6]
    # ])
    network['W1'] = np.random.rand(5,10)
    # network['W2'] = np.array([
    #     [0.2],
    #     [0.4],
    #     [0.6]
    # ])
    network['W2'] = np.random.rand(10,1)
    # network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.random.rand(10)
    # network['b2'] = np.array([0.1])
    network['b2'] = np.random.rand(1)
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
x = np.array([1., 2., 3., 4., 5.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[13.63762235  6.74770535  5.77446302  3.43357995  6.45307587  7.84504641
  6.44099899 11.25278934 10.26217915  6.43493579]
shape: (10,)

*** 中間層出力1 ***
[13.63762235  6.74770535  5.77446302  3.43357995  6.45307587  7.84504641
  6.44099899 11.25278934 10.26217915  6.43493579]
shape: (10,)

*** 総入力2 ***
[38.96929143]
shape: (1,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 78.28239623416204

##### 結果表示 #####
*** 中間層出力 ***
[13.63762235  6.74770535  5.77446302  3.43357995  6.45307587  7.84504641
  6.44099899 11.25278934 10.26217915  6.43493579]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 誤差 ***
-9.999999505838704e-08
shape: ()

